services:
  backend:
    build: ./backend
    image: ecommerce-backend
    container_name: mern-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - backend_logs:/app/logs
    networks:
      - mern-net

  frontend:
    build: ./frontend
    image: ecommerce-frontend
    container_name: mern-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-net

# ---------- Volumes ----------
volumes:
  backend_logs:

# ---------- Network ----------
networks:
  mern-net:
    driver: bridge

